/** Template 2 (Night Edition) — dark modal form chrome; use inside `pe-theme-night`. */
export const NIGHT_EDITION_REGISTER_FORM_SHELL =
  "space-y-4 text-[var(--pe-on-surface)] [&_button[type=submit]]:mt-2 [&_button[type=submit]]:flex [&_button[type=submit]]:w-full [&_button[type=submit]]:items-center [&_button[type=submit]]:justify-center [&_button[type=submit]]:gap-2 [&_button[type=submit]]:rounded-full [&_button[type=submit]]:bg-[linear-gradient(135deg,var(--pe-gradient-from),var(--pe-gradient-to))] [&_button[type=submit]]:py-4 [&_button[type=submit]]:text-sm [&_button[type=submit]]:font-bold [&_button[type=submit]]:text-[var(--pe-background)] [&_button[type=submit]]:shadow-[0_0_24px_rgba(255,169,249,0.35)] [&_button[type=submit]]:hover:opacity-90 " +
  "[&_button[type=button]]:rounded-lg [&_button[type=button]]:text-[var(--pe-on-surface-variant)] [&_label]:mb-1.5 [&_label]:block [&_label]:text-xs [&_label]:font-semibold [&_label]:uppercase [&_label]:tracking-wider [&_label]:text-[var(--pe-on-surface-variant)] " +
  "[&_input]:rounded-lg [&_input]:border [&_input]:border-white/10 [&_input]:bg-[var(--pe-surface-container-high)] [&_input]:px-4 [&_input]:py-3 [&_input]:text-base [&_input]:text-[var(--pe-on-surface)] [&_input]:placeholder:text-[var(--pe-on-surface-variant)]/60 [&_input]:shadow-none [&_input]:ring-0 [&_input:focus]:border-[color:var(--pe-primary)]/50 [&_input:focus]:ring-2 [&_input:focus]:ring-[color:var(--pe-primary)]/20 " +
  "[&_select]:rounded-lg [&_select]:border [&_select]:border-white/10 [&_select]:bg-[var(--pe-surface-container-high)] [&_select]:px-4 [&_select]:py-3 [&_select]:text-base [&_select]:text-[var(--pe-on-surface)] [&_select]:shadow-none [&_select]:ring-0 [&_select:focus]:border-[color:var(--pe-primary)]/50 " +
  "[&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-[var(--pe-surface-container-high)] [&_textarea]:text-[var(--pe-on-surface)] [&_p]:text-[var(--pe-on-surface-variant)] [&_span]:text-[var(--pe-on-surface-variant)] [&_.text-zinc-500]:text-[var(--pe-on-surface-variant)] [&_.text-zinc-600]:text-[var(--pe-on-surface-variant)] [&_.rounded-md.border]:border-white/10 [&_.rounded-md.border]:bg-[var(--pe-surface-container)]";

/** Template 3 (TechNexus) — brand-colored submit, same field chrome as Night Edition. */
/** Template 3 light — fields on white modal; brand CTA. */
export const TECH_NEXUS_LIGHT_REGISTER_FORM_SHELL =
  "space-y-4 text-[var(--pe-on-surface)] [&_button[type=submit]]:mt-2 [&_button[type=submit]]:flex [&_button[type=submit]]:w-full [&_button[type=submit]]:items-center [&_button[type=submit]]:justify-center [&_button[type=submit]]:gap-2 [&_button[type=submit]]:rounded-lg [&_button[type=submit]]:border-0 [&_button[type=submit]]:bg-[var(--pe-cta-bg,var(--pe-brand-vivid,#2e5bff))] [&_button[type=submit]]:py-3.5 [&_button[type=submit]]:text-base [&_button[type=submit]]:font-bold [&_button[type=submit]]:tracking-normal [&_button[type=submit]]:normal-case [&_button[type=submit]]:text-[var(--pe-cta-fg,#fff)] [&_button[type=submit]]:shadow-[0_10px_24px_-8px_rgba(46,91,255,0.4)] [&_button[type=submit]]:hover:bg-[#1e40af] [&_button[type=submit]]:disabled:opacity-60 " +
  "[&_button[type=button]]:rounded-lg [&_button[type=button]]:text-slate-600 [&_label]:mb-1.5 [&_label]:block [&_label]:text-xs [&_label]:font-semibold [&_label]:uppercase [&_label]:tracking-wider [&_label]:text-slate-600 " +
  "[&_input]:rounded-lg [&_input]:border [&_input]:border-slate-200 [&_input]:bg-white [&_input]:px-4 [&_input]:py-3 [&_input]:text-base [&_input]:text-slate-900 [&_input]:placeholder:text-slate-400 [&_input]:shadow-none [&_input]:ring-0 [&_input:focus]:border-[var(--pe-brand-vivid,#2e5bff)] [&_input:focus]:ring-2 [&_input:focus]:ring-[color-mix(in_srgb,var(--pe-brand-vivid,#2e5bff)_25%,transparent)] " +
  "[&_select]:rounded-lg [&_select]:border [&_select]:border-slate-200 [&_select]:bg-white [&_select]:px-4 [&_select]:py-3 [&_select]:text-base [&_select]:text-slate-900 [&_select]:shadow-none [&_select]:ring-0 [&_select:focus]:border-[var(--pe-brand-vivid,#2e5bff)] " +
  "[&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-slate-200 [&_textarea]:bg-white [&_textarea]:text-slate-900 [&_p]:text-slate-600 [&_span]:text-slate-600 [&_.text-zinc-500]:text-slate-500 [&_.text-zinc-600]:text-slate-600 [&_.rounded-md.border]:border-slate-200 [&_.rounded-md.border]:bg-slate-50";

export const TECH_NEXUS_REGISTER_FORM_SHELL =
  "space-y-4 text-[var(--pe-on-surface)] [&_button[type=submit]]:mt-2 [&_button[type=submit]]:flex [&_button[type=submit]]:w-full [&_button[type=submit]]:items-center [&_button[type=submit]]:justify-center [&_button[type=submit]]:gap-2 [&_button[type=submit]]:rounded-full [&_button[type=submit]]:border-0 [&_button[type=submit]]:bg-[var(--pe-cta-bg,var(--pe-tertiary-container))] [&_button[type=submit]]:py-4 [&_button[type=submit]]:text-sm [&_button[type=submit]]:font-bold [&_button[type=submit]]:uppercase [&_button[type=submit]]:tracking-wide [&_button[type=submit]]:text-[var(--pe-cta-fg,var(--pe-on-tertiary-container,#fff))] [&_button[type=submit]]:shadow-[0_12px_32px_-8px_color-mix(in_srgb,var(--pe-tertiary-container)_55%,transparent)] [&_button[type=submit]]:hover:brightness-95 [&_button[type=submit]]:disabled:opacity-60 " +
  "[&_button[type=button]]:rounded-lg [&_button[type=button]]:text-[var(--pe-on-surface-variant)] [&_label]:mb-1.5 [&_label]:block [&_label]:text-xs [&_label]:font-semibold [&_label]:uppercase [&_label]:tracking-wider [&_label]:text-[var(--pe-on-surface-variant)] " +
  "[&_input]:rounded-lg [&_input]:border [&_input]:border-white/10 [&_input]:bg-[var(--pe-surface-container-high)] [&_input]:px-4 [&_input]:py-3 [&_input]:text-base [&_input]:text-[var(--pe-on-surface)] [&_input]:placeholder:text-[var(--pe-on-surface-variant)]/60 [&_input]:shadow-none [&_input]:ring-0 [&_input:focus]:border-[color:var(--pe-tertiary-container)] [&_input:focus]:ring-2 [&_input:focus]:ring-[color-mix(in_srgb,var(--pe-tertiary-container)_35%,transparent)] " +
  "[&_select]:rounded-lg [&_select]:border [&_select]:border-white/10 [&_select]:bg-[var(--pe-surface-container-high)] [&_select]:px-4 [&_select]:py-3 [&_select]:text-base [&_select]:text-[var(--pe-on-surface)] [&_select]:shadow-none [&_select]:ring-0 [&_select:focus]:border-[color:var(--pe-tertiary-container)] " +
  "[&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-[var(--pe-surface-container-high)] [&_textarea]:text-[var(--pe-on-surface)] [&_p]:text-[var(--pe-on-surface-variant)] [&_span]:text-[var(--pe-on-surface-variant)] [&_.text-zinc-500]:text-[var(--pe-on-surface-variant)] [&_.text-zinc-600]:text-[var(--pe-on-surface-variant)] [&_.rounded-md.border]:border-white/10 [&_.rounded-md.border]:bg-[var(--pe-surface-container)]";

export const TECH_NEXUS_ENQUIRY_FORM_SHELL =
  "space-y-5 text-[var(--pe-on-surface)] [&_label]:mb-1.5 [&_label]:block [&_label]:text-xs [&_label]:font-semibold [&_label]:uppercase [&_label]:tracking-wider [&_label]:text-[var(--pe-on-surface-variant)] " +
  "[&_input]:rounded-lg [&_input]:border [&_input]:border-white/10 [&_input]:bg-[var(--pe-surface-container-high)] [&_input]:px-4 [&_input]:py-3 [&_input]:text-base [&_input]:text-[var(--pe-on-surface)] [&_input]:placeholder:text-[var(--pe-on-surface-variant)]/60 [&_input]:shadow-none [&_input]:ring-0 [&_input:focus]:border-[color:var(--pe-tertiary-container)] [&_input:focus]:ring-2 [&_input:focus]:ring-[color-mix(in_srgb,var(--pe-tertiary-container)_35%,transparent)] " +
  "[&_textarea]:min-h-[8rem] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-[var(--pe-surface-container-high)] [&_textarea]:px-4 [&_textarea]:py-3 [&_textarea]:text-sm [&_textarea]:text-[var(--pe-on-surface)] [&_textarea]:placeholder:text-[var(--pe-on-surface-variant)]/60 [&_textarea]:outline-none [&_textarea]:ring-0 [&_textarea:focus]:border-[color:var(--pe-tertiary-container)] [&_textarea:focus]:ring-2 [&_textarea:focus]:ring-[color-mix(in_srgb,var(--pe-tertiary-container)_35%,transparent)] " +
  "[&_button[type=submit]]:flex [&_button[type=submit]]:w-full [&_button[type=submit]]:items-center [&_button[type=submit]]:justify-center [&_button[type=submit]]:rounded-full [&_button[type=submit]]:border-0 [&_button[type=submit]]:bg-[var(--pe-cta-bg,var(--pe-tertiary-container))] [&_button[type=submit]]:py-3.5 [&_button[type=submit]]:text-sm [&_button[type=submit]]:font-bold [&_button[type=submit]]:uppercase [&_button[type=submit]]:tracking-wide [&_button[type=submit]]:text-[var(--pe-cta-fg,var(--pe-on-tertiary-container,#fff))] [&_button[type=submit]]:shadow-[0_12px_32px_-8px_color-mix(in_srgb,var(--pe-tertiary-container)_55%,transparent)] [&_button[type=submit]]:hover:brightness-95 [&_button[type=submit]]:disabled:opacity-60";

/** Night Edition enquiry form — matches registration field chrome. */
export const NIGHT_EDITION_ENQUIRY_FORM_SHELL =
  "space-y-5 text-[var(--pe-on-surface)] [&_label]:mb-1.5 [&_label]:block [&_label]:text-xs [&_label]:font-semibold [&_label]:uppercase [&_label]:tracking-wider [&_label]:text-[var(--pe-on-surface-variant)] " +
  "[&_input]:rounded-lg [&_input]:border [&_input]:border-white/10 [&_input]:bg-[var(--pe-surface-container-high)] [&_input]:px-4 [&_input]:py-3 [&_input]:text-base [&_input]:text-[var(--pe-on-surface)] [&_input]:placeholder:text-[var(--pe-on-surface-variant)]/60 [&_input]:shadow-none [&_input]:ring-0 [&_input:focus]:border-[color:var(--pe-primary)]/50 [&_input:focus]:ring-2 [&_input:focus]:ring-[color:var(--pe-primary)]/20 " +
  "[&_textarea]:min-h-[8rem] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-[var(--pe-surface-container-high)] [&_textarea]:px-4 [&_textarea]:py-3 [&_textarea]:text-sm [&_textarea]:text-[var(--pe-on-surface)] [&_textarea]:placeholder:text-[var(--pe-on-surface-variant)]/60 [&_textarea]:outline-none [&_textarea]:ring-0 [&_textarea:focus]:border-[color:var(--pe-primary)]/50 [&_textarea:focus]:ring-2 [&_textarea:focus]:ring-[color:var(--pe-primary)]/20 " +
  "[&_button[type=submit]]:flex [&_button[type=submit]]:w-full [&_button[type=submit]]:items-center [&_button[type=submit]]:justify-center [&_button[type=submit]]:rounded-full [&_button[type=submit]]:border-0 [&_button[type=submit]]:bg-[linear-gradient(135deg,var(--pe-gradient-from),var(--pe-gradient-to))] [&_button[type=submit]]:py-3.5 [&_button[type=submit]]:text-sm [&_button[type=submit]]:font-bold [&_button[type=submit]]:text-[var(--pe-background)] [&_button[type=submit]]:shadow-[0_0_24px_rgba(255,169,249,0.25)] [&_button[type=submit]]:hover:opacity-90 [&_button[type=submit]]:disabled:opacity-60";

/** Template 1 (Summit / professional light) form chrome — use inside `pe-theme-light` for readable fields. */
export const SUMMIT_REGISTER_FORM_SHELL =
  "font-register-body space-y-4 text-zinc-900 [&_button[type=submit]]:mt-2 [&_button[type=submit]]:flex [&_button[type=submit]]:w-full [&_button[type=submit]]:items-center [&_button[type=submit]]:justify-center [&_button[type=submit]]:gap-2 [&_button[type=submit]]:rounded-lg [&_button[type=submit]]:bg-zinc-950 [&_button[type=submit]]:py-4 [&_button[type=submit]]:font-register-display [&_button[type=submit]]:text-base [&_button[type=submit]]:font-semibold [&_button[type=submit]]:text-white [&_button[type=submit]]:shadow-none [&_button[type=submit]]:hover:opacity-90 " +
  "[&_button[type=button]]:rounded-lg [&_label]:mb-1 [&_label]:block [&_label]:text-xs [&_label]:font-bold [&_label]:uppercase [&_label]:tracking-wider [&_label]:text-on-surface-variant " +
  "[&_input]:rounded-lg [&_input]:border [&_input]:border-transparent [&_input]:bg-surface-container [&_input]:px-4 [&_input]:py-3 [&_input]:text-base [&_input]:text-zinc-900 [&_input]:shadow-none [&_input]:ring-0 [&_input:focus]:border-[color:var(--accent)] " +
  "[&_select]:rounded-lg [&_select]:border [&_select]:border-transparent [&_select]:bg-surface-container [&_select]:px-4 [&_select]:py-3 [&_select]:text-base [&_select]:text-zinc-900 [&_select]:shadow-none [&_select]:ring-0 [&_select:focus]:border-[color:var(--accent)] " +
  "[&_textarea]:text-zinc-900 [&_p]:text-zinc-700 [&_span]:text-zinc-700 [&_.rounded-md.border]:border-outline-variant/50 [&_.rounded-md.border]:bg-surface-container-low";
